#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

source "$HOME/.dev-machine/utils.bash"

install_antigen() {
  fancy_echo "Ｚ Installing antigen (for zsh management)..."
  mkdir -p ~/.config/antigen && curl -L git.io/antigen > ~/.config/antigen/antigen.zsh
}

if [ ! -f "$HOME/.config/antigen/antigen.zsh" ]; then
  install_antigen
fi
