#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

source "$HOME/.dev-machine/utils.bash"

if ! command -v apt-get > /dev/null; then
  fancy_echo "⏭ apt package manager not found, skipping..."
  exit 0
fi

fancy_echo "ℹ️ Setting up your machine using apt-get..."

install_packages() {
  sudo bash -c "apt-get install -y neovim ripgrep zsh git git-lfs fd-find >/dev/null 2>&1 & disown"
}

install_packages
