#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

source "$HOME/.dev-machine/utils.bash"

if [ "${SPIN:-0}" = "1" ]; then
  fancy_echo "⏭ Skipping in spin mode"
  exit 1
fi

install_astro() {
  git clone https://github.com/AstroNvim/AstroNvim ~/.config/nvim || git -C ~/.config/nvim pull
}

neovim_packages() {
  nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync' ||
    (nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerInstall' \
    && nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync')
}

install_astro && neovim_packages
