#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

source "$HOME/.dev-machine/utils.bash"

install_plugins() {
  fancy_echo "🔌 Installing nvim plugins"

  neovim_package_manager
  neovim_packages
}

neovim_package_manager() {
    local PACKER_DIRECTORY="${XDG_DATA_HOME:-$HOME/.local/share}/nvim/site/pack/packer/start/packer.nvim"

    if ! test -d  "$PACKER_DIRECTORY"; then
        fancy_echo 'Installing a package manager for Neovim...'
        quietly_run git clone "https://github.com/wbthomason/packer.nvim" "$PACKER_DIRECTORY"
    fi
}

neovim_packages() {
    nvim -u NONE \
        +'autocmd User PackerComplete quitall' \
        +'lua require("ianks.plugins")' \
        +'lua require("packer").sync()'
}

install_plugins
