#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

system_type=$(uname -s)

if [ "$system_type" == "Darwin" ]; then
  brew tap homebrew/cask-fonts
  brew install font-fira-code-nerd-font
  brew install font-jetbrains-mono-nerd-font
  brew install font-meslo-lg-nerd-font
fi
