#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

# Only run randomly 1/10 times
if [ "$RANDOM" -gt 3277 ]; then
  exit 0
else
  echo "⏳ Checking for dev-machine updates..."
fi


source "$HOME/.dev-machine/utils.bash"


if [ "$(uname -s)" == "Darwin" ]; then
  export PATH="$PATH:/opt/homebrew/bin"
fi

if command -v yadm > /dev/null; then
  quietly_run yadm pull || echo "WARNING: Could not update dev-machine (could not run yadm pull)"
else
  echo "ERROR: Could not update dev-machine (yadm not found)"
fi

version="$(cat $HOME/.dev-machine/version)"

if ! grep -Fxq "$version" "$HOME/.dev-machine/installed-version"; then
  echo "Updating dev-machine..."

  sleep 2

  chmod +x "$HOME/.config/yadm/bootstrap"

  if yadm bootstrap; then
    echo "$version" > "$HOME/.dev-machine/installed-version"
    echo "INFO: dev-machine update succeeded"
  else
    yadm upgrade || echo "ERROR: dev-machine update failed (could not upgrade yadm)"
    yadm bootstrap || echo "ERROR: dev-machine update failed (could not bootstrap yadm)"
  fi
fi

